version: '3.2'

services:
  web:
    labels:
      com.example.service: "web"
      com.example.description: "Use for the main web process"
    build:
      context: ./activityChallengeApi/docker_compose/django/
      dockerfile: Dockerfile
      args:
        requirements: requirements/production.txt
    image: activity_challenge_api_django_web:1.0
    depends_on:
      - db
    command: ["./activityChallengeApi/docker_compose/django/start.sh"]
    environment:
      PRODUCTION: 'true'
      PORT: 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"