version: '3.2'

services:

  web:
    labels:
      com.example.service: "web"
      com.example.description: "Use for the main web process"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements/development.txt
    image: activity_challenge_api_django_web:1.0
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      PRODUCTION: 'false'
    volumes:
      - .:/app
