FROM python:3

ENV PYTHONUNBUFFERED 1
ARG requirements=requirements/production.txt

RUN mkdir /code
WORKDIR /code

COPY . /code/
COPY requirements/ /code/requirements
COPY manage.py /code

RUN pip install -r $requirements

COPY start.sh /start.sh
CMD ["/start.sh"]