version: '3.2'

services:
  db:
    restart: always
    image: postgres
    container_name: activitychallenge_db
    volumes:
      - type: volume
        source: dbdata
        target: /pg_data
    ports:
      - "8001:5432"
  web:
    container_name: django_web
    environment: 
      - FITBIT_CLIENT_SECRET
      - FITBIT_CLIENT_ID
      - PORT

volumes:
  dbdata: