version: '3.2'

services:
  django_web:
    labels:
      com.example.service: "web"
      com.example.description: "Use for the main web process"
    build:
      context: ./activityChallengeApi/docker_compose/django/
      dockerfile: Dockerfile
      args:
        requirements: requirements/production.txt
    image: activity_challenge_api_django_web:1.0
    depends_on:
      - db
    command: ["./docker_compose/django/wait_for_postgres.sh"]
    environment:
      PRODUCTION: 'true'
    volumes:
      - .:/app
  nginx:
    restart: always
    container_name: nginx_server
    build:
      context: ./activityChallengeApi/docker_compose/nginx/
      dockerfile: Dockerfile
    depends_on:
      - django_web
    ports:
      - "0.0.0.0:80:80"