version: '2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5000
    env_file: .env.local
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db