# Generated by Django 2.1.4 on 2018-12-10 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DL', 'Daily'), ('WL', 'Weekly'), ('ML', 'Monthly')], default='DL', max_length=2)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PointSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_minute_points', models.IntegerField(default=2)),
                ('fat_zone_points', models.IntegerField(default=0)),
                ('cardio_zone_points', models.IntegerField(default=1)),
                ('peak_zone_points', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('competitions', models.ManyToManyField(to='api.Competition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='point_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.PointSystem'),
        ),
    ]
