# Generated by Django 2.1.4 on 2018-12-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181231_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='(Daily at 7 length = 7 days)',
            new_name='Length - (Daily type at 7 length = 7 days)',
        ),
    ]
