# Generated by Django 2.1.4 on 2018-12-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181231_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='length',
            field=models.IntegerField(help_text='e.g. Daily * 5 length = 5 days'),
        ),
    ]
