# Generated by Django 2.1.4 on 2019-01-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190106_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True, default=None),
            preserve_default=False,
        ),
    ]
