# Generated by Django 2.1.4 on 2019-01-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fitbit_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
