# Generated by Django 2.1.4 on 2019-01-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_fitbit_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('token', models.CharField(max_length=250)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
    ]
