# Generated by Django 2.1.4 on 2019-01-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_competitioninvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioninvitation',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitioninvitation',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
