# Generated by Django 2.1.4 on 2019-01-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190113_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='competitions',
            field=models.ManyToManyField(blank=True, to='api.Competition'),
        ),
    ]
