# Generated by Django 2.1.4 on 2019-01-24 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20190117_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_total', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='length',
        ),
        migrations.AddField(
            model_name='competition',
            name='end',
            field=models.DateField(default=datetime.datetime(2019, 1, 24, 18, 21, 20, 509352, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitionscore',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Competition'),
        ),
        migrations.AddField(
            model_name='competitionscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
