# Generated by Django 2.1.4 on 2019-01-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190124_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
