# Generated by Django 2.1.4 on 2019-01-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionscore',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition'),
        ),
        migrations.AlterField(
            model_name='competitionscore',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
